<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.3</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.test</groupId>
    <artifactId>LoadBalancerDemo</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>LoadBalancerDemo</name>
    <description>Demo project for load balancer</description>

    <properties>
        <java.version>11</java.version>
        <repackage.classifier/>
        <spring-native.version>0.12.1</spring-native.version>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>



    <dependencies>
        <dependency>
            <groupId>org.eclipse.paho</groupId>
            <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
            <version>1.2.5</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.13.3</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.13.3</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.jackson</groupId>
            <artifactId>jackson-xc</artifactId>
            <version>1.9.11</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-csv</artifactId>
            <version>1.8</version>
        </dependency>

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.13</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20210307</version>
        </dependency>

        <dependency>
            <groupId>com.github.docker-java</groupId>
            <artifactId>docker-java</artifactId>
            <version>3.3.4</version> <!-- Check for the latest version -->
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>spring-releases</id>
            <name>Spring Releases</name>
            <url>https://repo.spring.io/release</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>Eclipse Paho Repo</id>
            <url>https://repo.eclipse.org/content/repositories/paho-releases</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>spring-releases</id>
            <name>Spring Releases</name>
            <url>https://repo.spring.io/release</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
    <build>
        <!-- <extensions>
             <extension>
                 <groupId>org.apache.maven.wagon</groupId>
                 <artifactId>wagon-ssh</artifactId>
                 <version>3.4.3</version>
             </extension>
         </extensions>-->
        <plugins>
            <!-- Spring Boot Maven Plugin -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>1.8</version>
                <executions>
                    <execution>
                        <id>copy-to-intermediate</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <exec executable="sshpass">
                                    <arg value="-p"/>
                                    <arg value="rootPassword"/>
                                    <arg value="scp"/>
                                    <arg value="-o"/>
                                    <arg value="StrictHostKeyChecking=no"/>

                                    <arg value="/home/as00750/IdeaProjects/LoadBalancerDemo/target/LoadBalancerDemo-0.0.1-SNAPSHOT.jar"/>
                                    <arg value="mitra.shahabadi.1@ens.etsmtl.ca@VMIP:/tmp/"/>
                                </exec>
                            </target>
                        </configuration>
                    </execution>

                    <execution>
                        <id>copy-to-vm</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <exec executable="sshpass">
                                    <arg value="-p"/>
                                    <arg value="09371972490Msh"/>
                                    <arg value="ssh"/>
                                    <arg value="-o"/>
                                    <arg value="StrictHostKeyChecking=no"/>
                                    <arg value="mitra.shahabadi.1@ens.etsmtl.ca@VMIP"/>
                                    <arg value="sshpass"/>
                                    <arg value="-p"/>
                                    <arg value="VMPassword"/>
                                    <arg value="scp"/>
                                    <arg value="/tmp/LoadBalancerDemo-0.0.1-SNAPSHOT.jar"/>
                                    <arg value="as00750@192.168.122.98:/home/as00750"/>
                                </exec>
                            </target>
                        </configuration>
                    </execution>
                    <execution>
                        <id>remove-jar-from-tmp</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <exec executable="sshpass">
                                    <arg value="-p"/>
                                    <arg value="09371972490Msh"/>
                                    <arg value="ssh"/>
                                    <arg value="-o"/>
                                    <arg value="StrictHostKeyChecking=no"/>
                                    <arg value="mitra.shahabadi.1@ens.etsmtl.ca@VMIP"/>
                                    <!-- Path to your JAR file -->
                                    <arg value="rm"/>
                                    <arg value="-r"/>
                                    <arg value="/tmp/LoadBalancerDemo-0.0.1-SNAPSHOT.jar"/>
                                </exec>
                            </target>
                        </configuration>
                    </execution>
                </executions>
                <!-- <executions>
                     <execution>
                         <phase>package</phase>
                         <goals>
                             <goal>run</goal>
                         </goals>
                         <configuration>
                             <tasks>
                                 <scp todir="user@server:/path/to/target/directory">
                                     <fileset dir="${project.build.directory}">
                                         <include name="${project.build.finalName}.jar"/>
                                     </fileset>
                                 </scp>
                             </tasks>
                             <target>
                                 <exec executable="sshpass">
                                     <arg line="-p 'rootPassword' scp -o StrictHostKeyChecking=no -l 'mitra.shahabadi.1@ens.etsmtl.ca' target/LoadBalancerDemo-0.0.1-SNAPSHOT.jar VMIP:/tmp/"/>
                                 </exec>

                                 <exec executable="sshpass">
                                     <arg line="-p 'rootPassword' ssh -o StrictHostKeyChecking=no -l 'mitra.shahabadi.1@ens.etsmtl.ca' VMIP 'sshpass -p &quot;VMPassword&quot; scp -o StrictHostKeyChecking=no /tmp/LoadBalancerDemo-0.0.1-SNAPSHOT.jar as00750@serverIP:/home/as00750/'"/>
                                 </exec>

                                 <exec executable="sshpass">
                                     <arg line="-p 'rootPassword' ssh -o StrictHostKeyChecking=no -l 'mitra.shahabadi.1@ens.etsmtl.ca' VMIP 'rm /tmp/LoadBalancerDemo-0.0.1-SNAPSHOT.jar'"/>
                                 </exec>

                             </target>
                         </configuration>
                     </execution>
                 </executions>-->
            </plugin>
        </plugins>
    </build>


</project>
